name: Terraform Workflow

on:
  push:
    paths:
      - 'ecs/**'
      - 'lambda/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform Init
      run: terraform init

    - name: Check for changes
      id: check_changes
      run: echo "::set-output name=changed_folders::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(ecs|lambda)/[^/]+/')"

    - name: Apply Terraform changes
      if: steps.check_changes.outputs.changed_folders
      run: |
        for folder in ${steps.check_changes.outputs.changed_folders}; do
          cd $folder
          terraform apply -auto-approve
          cd -
        done