name: Terraform Conditional Apply

on:
  push:
    branches:
      - umair
    paths:
      - "ecs/**"
      - "lambda/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository # Make sure this line is correctly indented
        uses: actions/checkout@v2
      - name: Setup Terraform # This line should be at the same indentation level as the previous step
        uses: hashicorp/setup-terraform@v1
        with: # 'with' should align with 'uses'
          terraform_version: 1.0.0
      - name: Detect Changes
        run: |
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            # This is likely the first push to the repository, list all files
            CHANGED_DIRS=$(git ls-tree -r HEAD --name-only | grep -E '^(ecs|lambda)/' | awk 'BEGIN {FS="/"} {print $1"/"$2}' | uniq)
          else
            # Normal push, compare with the previous commit
            CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(ecs|lambda)/' | awk 'BEGIN {FS="/"} {print $1"/"$2}' | uniq)
          fi
          echo "Changed directories: $CHANGED_DIRS"
          echo "CHANGED_DIRS=$CHANGED_DIRS" >> $GITHUB_ENV
