name: Terraform Conditional Apply

on:
  push:
    paths:
      - 'ecs/**'
      - 'lambda/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Run Terraform on Modified Directories
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Detect Changes
        id: detect_changes
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(ecs|lambda)/' | awk 'BEGIN {FS="/"} {print $1"/"$2}' | uniq)
          echo "Changed directories: $CHANGED_DIRS"
          echo "::set-output name=changed_dirs::$CHANGED_DIRS"
      
      - name: Display Changed Directories
        run: echo "The following directories have changes: ${{ steps.detect_changes.outputs.changed_dirs }}"
