name: Dev Deploy ETLs

on:
  push:
    branches:
      - main
    paths:
      - "ecs-etls/**"

jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      # changed_directories: ${{ steps.set-output.outputs.changed_directories }}  
      matrix: ${{ steps.detect_changes.outputs.CHANGED_DIRS_JSON }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Changes
        id: detect_changes
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(ecs-etls)/' | awk 'BEGIN {FS="/"} {print $1"/"$2}' | uniq)
          CHANGED_DIRS_JSON=$(echo "$CHANGED_DIRS" | jq -R -s -c 'split("\n") | map(select(. != "")) | map({path: .}) | {include: .}')
          echo "CHANGED_DIRS_JSON=$CHANGED_DIRS_JSON" >> $GITHUB_OUTPUT
          echo $CHANGED_DIRS_JSON

  terraform-apply:
    runs-on: ubuntu-latest
    env:
      IMAGE_SCAN: true
    needs: find-out-changes
    strategy:
      matrix: ${{fromJson(needs.find-out-changes.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create ECR Repository
        run: |
          DIR_NAME="${{ matrix.path }}"
          IMAGE_NAME="${DIR_NAME#*/}" 
          if ! aws ecr describe-repositories --repository-names "$IMAGE_NAME" 2>/dev/null; then
            echo "Repository $IMAGE_NAME does not exist. Creating..."
            aws ecr create-repository --repository-name "$IMAGE_NAME" --image-scanning-configuration scanOnPush=$IMAGE_SCAN
          else
            echo "Repository $IMAGE_NAME already exists. Skipping creation."
          fi
      - name: Terraform step
        run: |
          echo ${{ matrix.path }}
          cd ${{ matrix.path }}/source
          ls -l
          
        

